export const AUTH_COLORS = {
    BACKGROUND_PRIMARY_COLOR: '#151515',
    BACKGROUND_SECONDARY_COLOR: '#1C1C1C',
    TEXT_PRIMARY_COLOR: '#D4D8DD',
    TEXT_SECONDARY_COLOR: '#C5C9CE',
    BORDER_COLOR: '#282828',
    INPUT_PLACEHOLDER_COLOR: '#CBCFD4',
    PRIMARY_BUTTON_BACKGROUND_COLOR_START: '#F33D7B',
    PRIMARY_BUTTON_BACKGROUND_COLOR_END: '#A044FF',
    GOOGLE_BUTTON_COLOR: '#FFFFFF',
    FACEBOOK_BUTTON_COLOR: '#1877F2',
    ERROR_COLOR: '#FF4D4F',
    SUCCESS_COLOR: '#4CAF50'
};